project:
  type: website
  output-dir: docs

website:
  title: "431 Project A"
  page-footer: "Fall 2025: PQHS/CRSP/MPHP 431 at CWRU with Professor Love"
  navbar:
    background: "#063970"
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: plan.qmd
        text: Plan
      - href: analyses.qmd
        text: Analyses
      - href: portfolio.qmd
        text: Portfolio
      - href: examples.qmd
        text: Examples

    right:
      - href: https://thomaselove.github.io/431-2025/contact.html
        text: "Contact Us"
      - href: https://thomaselove.github.io/431-2025
        text: "431 Homepage"

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    number-sections: true
    date-format: iso
    link-external-icon: true
    link-external-newwindow: true

editor: source
